#ifndef SYSCALLS_H
#define SYSCALLS_H

#define SYSCALL_LIST                                                           \
  X(read, 0)                                                                   \
  X(write, 1)                                                                  \
  X(open, 2)                                                                   \
  X(close, 3)                                                                  \
  X(stat, 4)                                                                   \
  X(fstat, 5)                                                                  \
  X(poll, 7)                                                                   \
  X(lseek, 8)                                                                  \
  X(mmap, 9)                                                                   \
  X(mprotect, 10)                                                              \
  X(munmap, 11)                                                                \
  X(brk, 12)                                                                   \
  X(sigaction, 13)                                                             \
  X(sigprocmask, 14)                                                           \
  X(ioctl, 16)                                                                 \
  X(pread, 17)                                                                 \
  X(pwrite, 18)                                                                \
  X(readv, 19)                                                                 \
  X(writev, 20)                                                                \
  X(access, 21)                                                                \
  X(pipe, 22)                                                                  \
  X(select, 23)                                                                \
  X(sched_yield, 24)                                                           \
  X(shmget, 29)                                                                \
  X(shmat, 30)                                                                 \
  X(shmctl, 31)                                                                \
  X(dup, 32)                                                                   \
  X(dup2, 33)                                                                  \
  X(nanosleep_time64, 35)                                                      \
  X(setitimer, 38)                                                             \
  X(getpid, 39)                                                                \
  X(socket, 41)                                                                \
  X(connect, 42)                                                               \
  X(accept, 43)                                                                \
  X(sendto, 44)                                                                \
  X(recvfrom, 45)                                                              \
  X(sendmsg, 46)                                                               \
  X(recvmsg, 47)                                                               \
  X(shutdown, 48)                                                              \
  X(bind, 49)                                                                  \
  X(listen, 50)                                                                \
  X(getsockname, 51)                                                           \
  X(getpeername, 52)                                                           \
  X(socketpair, 53)                                                            \
  X(setsockopt, 54)                                                            \
  X(getsockopt, 55)                                                            \
  X(fork, 56)                                                                  \
  X(exec, 59)                                                                  \
  X(exit, 60)                                                                  \
  X(waitpid, 61)                                                               \
  X(kill, 62)                                                                  \
  X(shmdt, 67)                                                                 \
  X(fcntl, 72)                                                                 \
  X(flock, 73)                                                                 \
  X(fsync, 74)                                                                 \
  X(fdatasync, 75)                                                             \
  X(truncate, 76)                                                              \
  X(ftruncate, 77)                                                             \
  X(getdents, 78)                                                              \
  X(getcwd, 79)                                                                \
  X(chdir, 80)                                                                 \
  X(fchdir, 81)                                                                \
  X(rename, 82)                                                                \
  X(mkdir, 83)                                                                 \
  X(rmdir, 84)                                                                 \
  X(link, 86)                                                                  \
  X(unlink, 87)                                                                \
  X(readlink, 89)                                                              \
  X(chmod, 90)                                                                 \
  X(fchmod, 91)                                                                \
  X(getuid, 102)                                                               \
  X(getgid, 104)                                                               \
  X(geteuid, 107)                                                              \
  X(getegid, 108)                                                              \
  X(getppid, 110)                                                              \
  X(mknod, 133)                                                                \
  X(statfs, 137)                                                               \
  X(fstatfs, 138)                                                              \
  X(gethostname, 170)                                                          \
  X(futex, 202)                                                                \
  X(epoll_create, 213)                                                         \
  X(clock_gettime, 228)                                                        \
  X(exit_group, 231)                                                           \
  X(epoll_wait, 232)                                                           \
  X(epoll_ctl, 233)                                                            \
  X(openat, 257)                                                               \
  X(unlinkat, 263)                                                             \
  X(readlinkat, 267)                                                           \
  X(sync_file_range, 277)                                                      \
  X(epoll_create1, 291)                                                        \
  X(dup3, 292)                                                                 \
  X(pipe2, 293)                                                                \
  X(prlimit64, 302)                                                            \
  X(getrandom, 318)

#endif
