; this config sets default policy to whitelist
;
; i.e. all the syscalls except the one defined
; in the blacklist are allowed to execute

[default]
whitelist


; whitelist is defined explicitly for the example
; purpose. Not adding it when [default] policy is set
; to whitelist won't make any difference. 
;
; this whitelist contains calls that should be allowed
; for successful execution of the provided `chmod` test.
 
[whitelist]
SYS_open
SYS_openat
SYS_close
SYS_unlink


; syscalls defined in the blacklisted will be
; denied.

[blacklist]
SYS_chmod
